export const workerData = [
  {
    "id": 1,
    "name": "রাহিম উদ্দিন",
    "skill": "ইলেকট্রিশিয়ান",
    "location": "ঢাকা, বাংলাদেশ",
    "experience": "৫ বছর",
    "availability": "সক্রিয়",
    "photo": "/images/workers/worker1.jpg",
    "contact": "017XXXXXXXX",
    "rating": 4.5,
    "reviews": 12,
    "bio": "আমি একজন অভিজ্ঞ ইলেকট্রিশিয়ান। বাড়ি ও অফিস উভয় ক্ষেত্রে কাজ করি।"
  },
  {
    "id": 2,
    "name": "করিম হোসেন",
    "skill": "প্লাম্বার",
    "location": "চট্টগ্রাম, বাংলাদেশ",
    "experience": "৩ বছর",
    "availability": "সক্রিয়",
    "photo": "/images/workers/worker2.jpg",
    "contact": "018XXXXXXXX",
    "rating": 4.7,
    "reviews": 9,
    "bio": "প্লাম্বিং কাজের অভিজ্ঞতা রয়েছে। জরুরি সেবা ও মেইনটেনেন্স করি।"
  },
  {
    "id": 3,
    "name": "জাহিদ আলী",
    "skill": "কার্পেন্টার",
    "location": "রাজশাহী, বাংলাদেশ",
    "experience": "৪ বছর",
    "availability": "সক্রিয়",
    "photo": "/images/workers/worker3.jpg",
    "contact": "019XXXXXXXX",
    "rating": 4.3,
    "reviews": 15,
    "bio": "আমি কাঠের কাজের দক্ষ কার্পেন্টার। ঘর ও অফিসের ফার্নিচার তৈরি করি।"
  },
  {
    "id": 4,
    "name": "ফারুক রহমান",
    "skill": "লেভার",
    "location": "সিলেট, বাংলাদেশ",
    "experience": "৬ বছর",
    "availability": "সক্রিয়",
    "photo": "/images/workers/worker4.jpg",
    "contact": "016XXXXXXXX",
    "rating": 4.8,
    "reviews": 20,
    "bio": "ভবন নির্মাণ ও দৈনিক ভারি কাজের অভিজ্ঞ মেসন।"
  },
  {
    "id": 5,
    "name": "মাহফুজুর রহমান",
    "skill": "পেইন্টার",
    "location": "বরিশাল, বাংলাদেশ",
    "experience": "৩ বছর",
    "availability": "সক্রিয়",
    "photo": "/images/workers/worker5.jpg",
    "contact": "017XXXXXXXX",
    "rating": 4.6,
    "reviews": 7,
    "bio": "ভর্তি এবং ইন্টেরিয়র পেইন্টিং কাজের দক্ষতা আছে।"
  },
  {
    "id": 6,
    "name": "আবুল কালাম",
    "skill": "গার্ড",
    "location": "খুলনা, বাংলাদেশ",
    "experience": "৫ বছর",
    "availability": "সক্রিয়",
    "photo": "/images/workers/worker6.jpg",
    "contact": "018XXXXXXXX",
    "rating": 4.4,
    "reviews": 11,
    "bio": "আমি নিরাপত্তা সেবায় অভিজ্ঞ। বিভিন্ন অফিস ও বাড়িতে গার্ডিং করি।"
  },
  {
    "id": 7,
    "name": "শফিকুল ইসলাম",
    "skill": "ড্রাইভার",
    "location": "ঢাকা, বাংলাদেশ",
    "experience": "৭ বছর",
    "availability": "সক্রিয়",
    "photo": "/images/workers/worker7.jpg",
    "contact": "019XXXXXXXX",
    "rating": 4.9,
    "reviews": 25,
    "bio": "প্রফেশনাল ড্রাইভার। নিরাপদ এবং নির্ভরযোগ্য গাড়ি চালানোর অভিজ্ঞতা।"
  },
  {
    "id": 8,
    "name": "রুবিনা খান",
    "skill": "হোম কেয়ার",
    "location": "চট্টগ্রাম, বাংলাদেশ",
    "experience": "৪ বছর",
    "availability": "সক্রিয়",
    "photo": "/images/workers/worker8.jpg",
    "contact": "016XXXXXXXX",
    "rating": 4.5,
    "reviews": 14,
    "bio": "বয়স্ক ও শিশুদের যত্নে অভিজ্ঞ হোম কেয়ার।"
  },
  {
    "id": 9,
    "name": "তাহসিন রহমান",
    "skill": "কম্পিউটার টেকনিশিয়ান",
    "location": "রাজশাহী, বাংলাদেশ",
    "experience": "৩ বছর",
    "availability": "সক্রিয়",
    "photo": "/images/workers/worker9.jpg",
    "contact": "017XXXXXXXX",
    "rating": 4.2,
    "reviews": 8,
    "bio": "কম্পিউটার ও ল্যাপটপ সার্ভিসিং ও মেইনটেনেন্সে দক্ষ।"
  },
  {
    "id": 10,
    "name": "মমতাজ বেগম",
    "skill": "ক্লিনার",
    "location": "সিলেট, বাংলাদেশ",
    "experience": "৫ বছর",
    "availability": "সক্রিয়",
    "photo": "/images/workers/worker10.jpg",
    "contact": "018XXXXXXXX",
    "rating": 4.6,
    "reviews": 10,
    "bio": "ঘর ও অফিস ক্লিনিংয়ে অভিজ্ঞ। সার্ভিস দ্রুত এবং নির্ভরযোগ্য।"
  }
]
